### ISSUE TITLE
openSUSE Tumbleweed: не отображается значок в системном лотке панели KDE.

### ISSUE THREAD

**Issue by aaly11** [ddanilov/soundscape#4]
Привет.
В чём может быть причина "невидимости" значка в системном лотке панели KDE?
KDE Plasma: 6.1.5
KDE Frameworks: 6.6.0
Qt: 6.7.2
Wayland или X11 не суть.
На панели LXQt значок приложения замещается другим, похожим на рамку окна с восклицательным знаком по середине.
Только на панельке tint2 в openbox значок по прежнему виден.

**Comment by aaly11** [comment]
[![KDE](https://paste.opensuse.org/pastes/2906611bfe33/raw)](https://paste.opensuse.org/pastes/2906611bfe33/raw)
[![LXQt](https://paste.opensuse.org/pastes/2d1bf4245044/raw)](https://paste.opensuse.org/pastes/2d1bf4245044/raw)

**Comment by ddanilov** [comment]
потестировал Tumbleweed в виртуальной машине: да есть такой баг...

> В чём может быть причина "невидимости" значка в системном лотке панели KDE?

КДЕшники что-то намудрили с трейем (ну и LXQt с ними за компанию), на той же системе в MATE и Xfce всё нормально работает. Сделаю потом небольшое исправление на такой случай.
